### ISSUE TITLE
doki x doki sasete broken sprites

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#12]
broken sprites in 9228f9480b910ba16709a79cc647e166f5deb5ac

![2018-11-14-230944_](https://user-images.githubusercontent.com/32330689/48518849-d3a44f80-e862-11e8-8808-37a66caed344.png)

**Comment by philj56** [comment]
I think that's the wrong commit, it's actually ffb42fea659769889889deba1dc946259d1b2791. Either way, at first glance this is due to a broken HDMA implementation

**Comment by philj56** [comment]
This has been fixed in 6b5778937cf2e5c08162deccd78e2e0cbafd95f5. The game was being told that the HDMA transfer had finished immediately, causing it to start switching ROM banks, so that the HDMA transfers were from random places in memory giving the corrupted sprites seen.
