### ISSUE TITLE
doki x doki sasete audio bad

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#13]
started in commit f4dce20a4afa83aba5711b62cd4557bd283270ba

audio bad. looks like it's just the wav channel that is wrong

**Comment by philj56** [comment]
Should be fixed in e7956fbcdfb9dd0ceeeba47a8ddff3501c5cbbcc.

**Comment by philj56** [comment]
Actually this fix breaks e.g. Pokemon Yellow - something else is amiss here

**Comment by philj56** [comment]
Fixed properly in 59a04ef82be3712050296fd4806754f73ba56d8d
