### ISSUE TITLE
Shantae

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#17]
1. Black screen during main menu screens and when entering a new area in game. Solved by entering the pause menu with START.

2. Still seems to be some sprite ordering issues

![2019-12-31t16 51 51z](https://user-images.githubusercontent.com/32330689/50564749-9d8e3280-0d1f-11e9-8041-9198c213c9b4.png)
![2019-12-31t17 06 19z](https://user-images.githubusercontent.com/32330689/50564754-a41caa00-0d1f-11e9-824d-723e2bfe3397.png)

3. Some glitchy effects occasionally happen on some scene transitions

![2019-12-31t16 55 58z](https://user-images.githubusercontent.com/32330689/50564769-c0b8e200-0d1f-11e9-9071-2dcfeb3c35f4.png)

4. I'm not sure if this of use to you but a flood of messages appear at the start of the first proper level after the intro sequence:
> [DEBUG]: SRAM not enabled!
[ERROR]: Reading memory address 0xB9B4 out of bounds.

with various 0xB*** memory addresses. Doesn't seem to happen at any other time.

**Comment by philj56** [comment]
This'll probably all get sorted when I get around to rewriting all of the ppu stuff, it's a bit off a mess at the moment.

**Comment by philj56** [comment]
As predicted, this is finally all fixed in 4bc7da7a6e2dec75ea2741485a9284dba2f695ee (apart from the SRAM issues.) Gotta haul booty!
