### ISSUE TITLE
Floppy fish boy causes Metroid 2 to seg fault

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#2]
![2018-06-21-210538_](https://user-images.githubusercontent.com/32330689/41743071-cea3aa5a-7597-11e8-8502-ade1bcfa8716.png)

**Comment by georgehb** [comment]
Also HUD is too far to the right and cuts off

**Comment by philj56** [comment]
This was due to a ROM banking issue - fixed in 98ada7ce6e6ed26fb60423433cbc99363caf807f
