### ISSUE TITLE
Megaman_Xtreme_2 missing cursor

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#20]
![2019-05-29-213220](https://user-images.githubusercontent.com/32330689/58590181-72baf280-825b-11e9-9c77-450cb70cfa08.png)

When selecting to continue from a save file, there should be a cursor arrow pointing to either the "Yes" or the "No".

This seems to only be a problem with the window, as the cursor appears when it's just the background

**Comment by philj56** [comment]
Finally fixed in ecbe97deaf899e29759373ea18c950756e3596cb.
