### ISSUE TITLE
Soul Falchion crashes with Invalid opcode

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#21]
![2019-05-29-222329](https://user-images.githubusercontent.com/32330689/58592560-a2b8c480-8260-11e9-85b9-5677424a7bac.png)

After waiting at the main menu for a few seconds gbcc exits with error
>[ERROR]: Invalid opcode: 0xEB

**Comment by philj56** [comment]
This seems to have been fixed in f3c64149607406f11477c3211890cf91d460321c.
