### ISSUE TITLE
Incorrect display of the minimized window.

### ISSUE THREAD

**Issue by mxlgv** [philj56/gbcc#24]
Hello! I think it would be nice to specify the minimum window size to avoid this:
![image](https://user-images.githubusercontent.com/51446645/95632834-29092b80-0a8f-11eb-9955-4e614b3aca19.png)

**Comment by philj56** [comment]
Yep good idea, it's really a bug that this is even possible at the moment.

**Comment by philj56** [comment]
Fixed in b8cc1905a0c2e697d57d28884ca7ccf759c58ce5.

**Comment by mxlgv** [comment]
Cool! You fixed it!

пн, 12 окт. 2020 г., 19:02 Philip Jones <notifications@github.com>:
