### ISSUE TITLE
Tetris Blast

### ISSUE THREAD

**Issue by Nekosis** [philj56/gbcc#25]
Every other piece in Tetris Blast is invisible. Pausing and unpausing twice seems to fix the problem. Footage captured on Android version of GBCC using a Samsung Galaxy A51:
https://drive.google.com/file/d/1mJxC_sn8dHRBkIweBlhcggoqqY5ueRRu/view?usp=drivesdk

**Comment by philj56** [comment]
Thanks for reporting this! It looks like this bug manages to go all the way back to 79c0f2771382bb8ad4c89e85d90caa594a4cb15a in 2018, which is impressive. I'll look into it, though I don't have the time to make another release of gbcc at the moment so it won't be fixed on android for quite some time.

**Comment by philj56** [comment]
Fixed in ecbe97deaf899e29759373ea18c950756e3596cb.
