### ISSUE TITLE
A+B buttons: can't press them together

### ISSUE THREAD

**Issue by farvardin** [philj56/gbcc#28]
Hello, 

Some games or applications on the gameboy require to press A+B simultanously (for example lsdj). 

It seems gbcc doesn't allow this, at least not on android

**Comment by philj56** [comment]
Hi, yeah sorry that's fixed locally but I don't think I've made a fixed release on android. You should be able to press both A+B at the same time with one finger (e.g. press A, then slide your finger onto B) - I put that in to make games like Super Mario playable, but I think I broke normal pressing at the same time.

I'll make an updated release soon-ish and let you know.

**Comment by philj56** [comment]
Ok, so I've finally made a release and started rolling it out to Android. Should be available within the next couple of days - sorry for being so slow on this!

**Comment by farvardin** [comment]
thank you very much!
