### ISSUE TITLE
Metroid 2: Minor Graphical glitches

### ISSUE THREAD

**Issue by georgehb** [philj56/gbcc#6]
**Glitch 1**

When this enemy is just off screen, incorrect sprites are shown

![2018-06-24-144738_](https://user-images.githubusercontent.com/32330689/41820496-a72e68f4-77ca-11e8-90ab-9b70d05b10c7.png)

Easily seen when standing on the lower ledge, sprite flickers rapidly between the two shown screen shots

![2018-06-24-144743_](https://user-images.githubusercontent.com/32330689/41820510-ed72f7d0-77ca-11e8-86f1-e10708370ce5.png)

![2018-06-24-160941_](https://user-images.githubusercontent.com/32330689/41820521-11a6891e-77cb-11e8-88ad-3797d0b3df1d.png)

In mGBA the enemy is not visible at all from lower ledge

**Glitch 2**

When loading from a save, the save room loads incorrectly
![2018-06-24-144957_](https://user-images.githubusercontent.com/32330689/41820586-ea199dd6-77cb-11e8-9072-a285b6f90672.png)

These glitches are more than just graphical and can even be stood on

![2018-06-24-151749_](https://user-images.githubusercontent.com/32330689/41820594-0be02020-77cc-11e8-8643-2d4bc579cde3.png)

And Samus can fit in the blank space in the collumn whilst a ball

![2018-06-24-162627_](https://user-images.githubusercontent.com/32330689/41820600-205ae44a-77cc-11e8-8aa4-9fb8912f65b7.png)

Once you move the incriminating tiles off screen they then loads normally. This error has only been found to occur when first starting up the game

Unbroken room for comparison

![2018-06-24-145021_](https://user-images.githubusercontent.com/32330689/41820623-a4b21830-77cc-11e8-85b9-e2fb752d0cd1.png)

**Comment by georgehb** [comment]
Here is a nearby save for Glitch 1. Head right until you reach a tall vertical room it's the first enemy at the top of this room

![metroid2 sav](https://user-images.githubusercontent.com/32330689/41826160-42bbeb1c-781f-11e8-90e8-8192cb0e119f.jpg)

(I had to save as an image so just rename the file)

**Comment by philj56** [comment]
Note to self: this is definitely in `gbcc_ppu.c`

**Comment by philj56** [comment]
The first glitch should be solved in c32eaab28f2ff4c83f2a7f1a2b3576e7eca77f23. It was being caused by a negative overflow in the ppu when an 8x8 sprite was within the top 8 pixels of the screen.

**Comment by philj56** [comment]
At long last this can be closed I think - the saves got fixed somewhere in 0d4fa8b52d6f79e10319135f9c7d676a213607a7. No more magical glitch world exploration.
